### ISSUE TITLE
can't receive new data after a period of inactivity on susbcribe method

### ISSUE THREAD

**Issue by ahmedJD** [wallforfry/dart_mercure#7]
hello , i'm using this plugin with symfony backend. it's working perfectly but when i open a page after a time of inactivity i don't receive  the new data after subscribe to topics. any one have an idea about that?

**Comment by fif1973** [comment]
same problem, no error in app logs

**Comment by fif1973** [comment]
I solved this problem on server side by restarting Mercure server with -**-write-timeout=0**
